# Generated by Django 4.0.5 on 2022-07-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_district_state_subdistrict_district_state_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
