# Generated by Django 4.0.5 on 2022-07-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipdate',
            field=models.DateField(),
        ),
    ]
