# Generated by Django 4.0.5 on 2022-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('CANCEL', 'CANCEL'), ('SHIPPING', 'SHIPPING'), ('SHIPED', 'SHIPED')], max_length=200, null=True),
        ),
    ]
