# Generated by Django 4.0.5 on 2022-08-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
