# Generated by Django 4.0.5 on 2022-08-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_banner_description_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
