# Generated by Django 4.0.5 on 2022-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('Description', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='blog')),
                ('date', models.DateField()),
            ],
        ),
    ]
